#!/bin/sh
rm -f /tmp/docker.log
touch /tmp/docker.log

NIC=`ifconfig -s | grep enp | awk '{print $1}'`
IP=`ifconfig $NIC | grep 'inet ' | awk '{print $2}'`

while [ -z $IP ]
do
    sleep 1
    IP=`ifconfig $NIC | grep 'inet ' | awk '{print $2}'`
done

echo "IP: $IP" >> /tmp/docker.log

sed -i -e "s;is:.*;is: $IP;" /etc/issue

cd /srv/demo-clut-clpa/

sed -i -e "s;PUBLICHOST:.*;PUBLICHOST: $IP;" docker-compose.yml

docker-compose down
docker-compose up -d

date >> /tmp/docker.log

if [ $? -eq 0 ]; then
    echo 'docker start successfully' >> /tmp/docker.log
else
    echo 'docker start failly' >> /tmp/docker.log
fi

docker ps -a >> /tmp/docker.log

systemctl restart getty@tty1

